/* Copyright (C) 2017 Taylor Holberton
 *
 * This file is part of Swanson.
 *
 * Swanson is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Swanson is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Swanson.  If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by the Swanson
 * resource compiler. It contains the data
 * of an ELF file, compiled by:
 *
 *   moxie-elf-gcc test.c -nostartfiles
 *
 * Where the version of GCC is 8.0.0 and
 * the source of 'test.c' is simply this:
 *
 *   void
 *   _start(void) {
 *
 *   }
 *
 * This ELF file is used for testing the
 * code that reads ELF files.
 *
 * Here's the output of:
 *
 *   readelf a.out --section-headers
 *
 * Where 'a.out' this the ELF file in
 * this file.
 *
 *   There are 6 section headers, starting at offset 0x168:
 *   
 *   Section Headers:
 *     [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
 *     [ 0]                   NULL            00000000 000000 000000 00      0   0  0
 *     [ 1] .text             PROGBITS        00001000 000054 000004 00  AX  0   0  2
 *     [ 2] .comment          PROGBITS        00000000 000058 000029 01  MS  0   0  1
 *     [ 3] .symtab           SYMTAB          00000000 000084 000090 10      4   4  4
 *     [ 4] .strtab           STRTAB          00000000 000114 000027 00      0   0  1
 *     [ 5] .shstrtab         STRTAB          00000000 00013b 00002a 00      0   0  1
 *   Key to Flags:
 *     W (write), A (alloc), X (execute), M (merge), S (strings)
 *     I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
 *     O (extra OS processing required) o (OS specific), p (processor specific)
 *
 * */

#ifndef SWANSON_RC_ELF_DATA_H
#define SWANSON_RC_ELF_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

extern const void *elf_data;

extern const unsigned long int elf_data_size;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SWANSON_RC_ELF_DATA_H */
